# Generated by Django 2.2.2 on 2019-08-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('base_currency', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNameGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr', models.CharField(blank=True, max_length=255, null=True)),
                ('en', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.CompanyBase')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('quarter', models.IntegerField(null=True)),
                ('asset', models.BigIntegerField(null=True)),
                ('capital', models.BigIntegerField(null=True)),
                ('liabilities', models.BigIntegerField(null=True)),
                ('sales', models.BigIntegerField(null=True)),
                ('operating_revenue', models.BigIntegerField(null=True)),
                ('net_income', models.BigIntegerField(null=True)),
                ('total_share', models.BigIntegerField(null=True)),
                ('foreigner_share', models.BigIntegerField(null=True)),
                ('quarter_check', models.BooleanField(default=False)),
                ('ratio', models.CharField(max_length=100, null=True)),
                ('ratio_found', models.BooleanField(null=True)),
                ('ratio_unity', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('ifrs', models.BooleanField(null=True)),
                ('gaap', models.BooleanField(null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.CompanyBase')),
            ],
        ),
    ]
