# Generated by Django 2.2.2 on 2019-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='ratio_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='ratio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
