# Generated by Django 2.2.2 on 2019-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190807_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='market_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
