# Generated by Django 2.2.2 on 2019-08-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_companydata_market_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='quarter',
            new_name='quarter_model',
        ),
        migrations.RenameField(
            model_name='companydata',
            old_name='year',
            new_name='year_model',
        ),
    ]
