# Generated by Django 2.2.2 on 2019-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190812_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
