# Generated by Django 2.2.2 on 2020-01-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_companydata_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRL_CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_model', models.IntegerField(null=True)),
                ('quarter_model', models.IntegerField(null=True)),
                ('asset', models.BigIntegerField(null=True)),
                ('capital', models.BigIntegerField(null=True)),
                ('liabilities', models.BigIntegerField(null=True)),
                ('sales', models.BigIntegerField(null=True)),
                ('operating_revenue', models.BigIntegerField(null=True)),
                ('net_income', models.BigIntegerField(null=True)),
                ('total_share', models.BigIntegerField(null=True)),
                ('foreigner_share', models.BigIntegerField(null=True)),
                ('quarter_check', models.BooleanField(default=False)),
                ('ratio', models.CharField(max_length=500, null=True)),
                ('ratio_count', models.IntegerField(null=True)),
                ('ratio_found', models.BooleanField(null=True)),
                ('ratio_unity', models.BooleanField(null=True)),
                ('market_code', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('ifrs', models.BooleanField(null=True)),
                ('gaap', models.BooleanField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.CompanyBase')),
            ],
        ),
    ]
