# Generated by Django 2.2.2 on 2020-01-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_xbrl_companydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_model', models.IntegerField()),
                ('year_model', models.IntegerField()),
                ('error', models.BooleanField(null=True)),
                ('error_code', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('edited_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
