# Generated by Django 2.2.2 on 2020-02-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_xbrlverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='ratio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
