# Generated by Django 2.2.2 on 2020-02-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200205_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='xbrl_companydata',
            name='ratio',
        ),
    ]
